export const Colorways: string[] = [
    "Closest color?",
    "Black",
    "Blue",
    "Blue-green",
    "Blue-purple",
    "Brown",
    "Gray",
    "Green",
    "Multicolored",
    "Natural/Undyed",
    "Orange",
    "Pink",
    "Purple",
    "Rainbow\t",
    "Red",
    "Red-orange",
    "Red-purple",
    "White",
    "Yellow",
    "Yellow-green",
    "Yellow-orange",
];

export const Yarnweight: string[] = [
    "Thread",
    "Cobweb",
    "Lace",
    "Light Fingering",
    "Fingering (14 wpi)",
    "Sport (12 wpi)",
    "DK (11 wpi)",
    "Worsted (9 wpi)",
    "Aran (8 wpi)",
    "Bulky (7 wpi)",
    "Super Bulky (5-6 wpi)",
    "Jumbo (0-4 wpi)",
];

export const Currency: string[] = [
    "USD: U.S. $",
    "AUD: Australian $",
    "BRL: Real",
    "CAD: Canadian $",
    "CHF: Francs",
    "CZK: Koruna",
    "DKK: Kroner",
    "EUR: Euros",
    "GBP: Sterling",
    "HKD: Hong Kong $",
    "HRK: Kuna",
    "HUF: Forint",
    "ILS: NIS",
    "INR: Rupee",
    "ISK: króna",
    "JPY: Yen",
    "MXN: Mexican $",
    "NOK: Kroner",
    "NZD: New Zealand $",
    "PLN: Złoty",
    "RUB: Ruble",
    "SEK: Kronor",
    "SGD: Singapore $",
    "TWD: New Taiwan $",
    "ZAR: Rand",
];

export const HookSizes = [
    { value: "25", text: "0.6 mm" },
    { value: "26", text: "0.7 mm" },
    { value: "27", text: "0.75 mm" },
    { value: "28", text: "0.85 mm" },
    { value: "29", text: "0.9 mm" },
    { value: "30", text: "1.0 mm" },
    { value: "31", text: "1.05 mm" },
    { value: "47", text: "1.1 mm" },
    { value: "32", text: "1.1 mm" },
    { value: "33", text: "1.15 mm" },
    { value: "34", text: "1.25 mm" },
    { value: "35", text: "1.3 mm" },
    { value: "36", text: "1.4 mm" },
    { value: "37", text: "1.5 mm" },
    { value: "38", text: "1.65 mm" },
    { value: "22", text: "1.75 mm" },
    { value: "44", text: "1.8 mm" },
    { value: "45", text: "1.9 mm" },
    { value: "19", text: "2.0 mm" },
    { value: "46", text: "2.1 mm" },
    { value: "1", text: "2.25 mm (B)" },
    { value: "50", text: "2.35 mm" },
    { value: "21", text: "2.5 mm" },
    { value: "2", text: "2.75 mm (C)" },
    { value: "20", text: "3.0 mm" },
    { value: "3", text: "3.25 mm (D)" },
    { value: "4", text: "3.5 mm (E)" },
    { value: "5", text: "3.75 mm (F)" },
    { value: "6", text: "4.0 mm (G)" },
    { value: "49", text: "4.25 mm (G)" },
    { value: "7", text: "4.5 mm" },
    { value: "8", text: "5.0 mm (H)" },
    { value: "9", text: "5.5 mm (I)" },
    { value: "10", text: "6.0 mm (J)" },
    { value: "11", text: "6.5 mm (K)" },
    { value: "23", text: "7.0 mm" },
    { value: "24", text: "7.5 mm" },
    { value: "12", text: "8.0 mm (L)" },
    { value: "13", text: "9.0 mm (M/N)" },
    { value: "14", text: "10.0 mm (N/P)" },
    { value: "51", text: "11.5 mm (P)" },
    { value: "15", text: "12.0 mm" },
    { value: "48", text: "12.0 mm" },
    { value: "16", text: "15.0 mm (P/Q)" },
    { value: "52", text: "15.75 mm (Q)" },
    { value: "17", text: "19.0 mm (S)" },
    { value: "18", text: "25.0 mm" },
    { value: "53", text: "40.0 mm" },
];

export const NeedleSizes = [
    { value: "43", text: "US 00000000 - 0.5 mm" },
    { value: "42", text: "US 000000 - 0.75 mm" },
    { value: "41", text: "US 00000 - 1.0 mm" },
    { value: "40", text: "US 0000 - 1.25 mm" },
    { value: "39", text: "US 000 - 1.5 mm" },
    { value: "22", text: "US 00 - 1.75 mm" },
    { value: "19", text: "US 0 - 2.0 mm" },
    { value: "1", text: "US 1  - 2.25 mm" },
    { value: "21", text: "US 1½ - 2.5 mm" },
    { value: "2", text: "US 2  - 2.75 mm" },
    { value: "20", text: "US 2½ - 3.0 mm" },
    { value: "3", text: "US 3  - 3.25 mm" },
    { value: "4", text: "US 4  - 3.5 mm" },
    { value: "5", text: "US 5  - 3.75 mm" },
    { value: "6", text: "US 6  - 4.0 mm" },
    { value: "49", text: "4.25 mm" },
    { value: "7", text: "US 7  - 4.5 mm" },
    { value: "55", text: "4.75 mm" },
    { value: "8", text: "US 8  - 5.0 mm" },
    { value: "9", text: "US 9  - 5.5 mm" },
    { value: "10", text: "US 10  - 6.0 mm" },
    { value: "11", text: "US 10½ - 6.5 mm" },
    { value: "23", text: "7.0 mm" },
    { value: "24", text: "7.5 mm" },
    { value: "12", text: "US 11  - 8.0 mm" },
    { value: "13", text: "US 13  - 9.0 mm" },
    { value: "14", text: "US 15  - 10.0 mm" },
    { value: "15", text: "US 17  - 12.0 mm" },
    { value: "16", text: "US 19  - 15.0 mm" },
    { value: "17", text: "US 35  - 19.0 mm" },
    { value: "18", text: "US 50  - 25.0 mm" },
];

export const NeedleMap = new Map([
    ["43", "US 00000000 - 0.5 mm"],
    ["42", "US 000000 - 0.75 mm"],
    ["41", "US 00000 - 1.0 mm"],
    ["40", "US 0000 - 1.25 mm"],
    ["39", "US 000 - 1.5 mm"],
    ["22", "US 00 - 1.75 mm"],
    ["19", "US 0 - 2.0 mm"],
    ["1", "US 1  - 2.25 mm"],
    ["21", "US 1½ - 2.5 mm"],
    ["2", "US 2  - 2.75 mm"],
    ["20", "US 2½ - 3.0 mm"],
    ["3", "US 3  - 3.25 mm"],
    ["4", "US 4  - 3.5 mm"],
    ["5", "US 5  - 3.75 mm"],
    ["6", "US 6  - 4.0 mm"],
    ["49", "4.25 mm"],
    ["7", "US 7  - 4.5 mm"],
    ["55", "4.75 mm"],
    ["8", "US 8  - 5.0 mm"],
    ["9", "US 9  - 5.5 mm"],
    ["10", "US 10  - 6.0 mm"],
    ["11", "US 10½ - 6.5 mm"],
    ["23", "7.0 mm"],
    ["24", "7.5 mm"],
    ["12", "US 11  - 8.0 mm"],
    ["13", "US 13  - 9.0 mm"],
    ["14", "US 15  - 10.0 mm"],
    ["15", "US 17  - 12.0 mm"],
    ["16", "US 19  - 15.0 mm"],
    ["17", "US 35  - 19.0 mm"],
    ["18", "US 50  - 25.0 mm"],
]);

export const HookMap = new Map([
    ["25", "0.6 mm"],
    ["26", "0.7 mm"],
    ["27", "0.75 mm"],
    ["28", "0.85 mm"],
    ["29", "0.9 mm"],
    ["30", "1.0 mm"],
    ["31", "1.05 mm"],
    ["47", "1.1 mm"],
    ["32", "1.1 mm"],
    ["33", "1.15 mm"],
    ["34", "1.25 mm"],
    ["35", "1.3 mm"],
    ["36", "1.4 mm"],
    ["37", "1.5 mm"],
    ["38", "1.65 mm"],
    ["22", "1.75 mm"],
    ["44", "1.8 mm"],
    ["45", "1.9 mm"],
    ["19", "2.0 mm"],
    ["46", "2.1 mm"],
    ["1", "2.25 mm (B)"],
    ["50", "2.35 mm"],
    ["21", "2.5 mm"],
    ["2", "2.75 mm (C)"],
    ["20", "3.0 mm"],
    ["3", "3.25 mm (D)"],
    ["4", "3.5 mm (E)"],
    ["5", "3.75 mm (F)"],
    ["6", "4.0 mm (G)"],
    ["49", "4.25 mm (G)"],
    ["7", "4.5 mm"],
    ["8", "5.0 mm (H)"],
    ["9", "5.5 mm (I)"],
    ["10", "6.0 mm (J)"],
    ["11", "6.5 mm (K)"],
    ["23", "7.0 mm"],
    ["24", "7.5 mm"],
    ["12", "8.0 mm (L)"],
    ["13", "9.0 mm (M/N)"],
    ["14", "10.0 mm (N/P)"],
    ["51", "11.5 mm (P)"],
    ["15", "12.0 mm"],
    ["48", "12.0 mm"],
    ["16", "15.0 mm (P/Q)"],
    ["52", "15.75 mm (Q)"],
    ["17", "19.0 mm (S)"],
    ["18", "25.0 mm"],
    ["53", "40.0 mm"],
]);

export const Country = [
    { value: "notselected", text: "" },
    { value: "13", text: "Australia" },
    { value: "39", text: "Canada" },
    { value: "84", text: "Germany" },
    { value: "228", text: "United Kingdom" },
    { value: "229", text: "United States" },
    { value: "1", text: "Afghanistan" },
    { value: "2", text: "Albania" },
    { value: "3", text: "Algeria" },
    { value: "4", text: "American Samoa" },
    { value: "5", text: "Andorra" },
    { value: "6", text: "Angola" },
    { value: "7", text: "Anguilla" },
    { value: "8", text: "Antarctica" },
    { value: "9", text: "Antigua And Barbuda" },
    { value: "10", text: "Argentina" },
    { value: "11", text: "Armenia" },
    { value: "12", text: "Aruba" },
    { value: "13", text: "Australia" },
    { value: "14", text: "Austria" },
    { value: "15", text: "Azerbaijan" },
    { value: "16", text: "Bahamas" },
    { value: "17", text: "Bahrain" },
    { value: "18", text: "Bangladesh" },
    { value: "19", text: "Barbados" },
    { value: "20", text: "Belarus" },
    { value: "21", text: "Belgium" },
    { value: "22", text: "Belize" },
    { value: "23", text: "Benin" },
    { value: "24", text: "Bermuda" },
    { value: "25", text: "Bhutan" },
    { value: "26", text: "Bolivia" },
    { value: "27", text: "Bosnia and Herzegowina" },
    { value: "28", text: "Botswana" },
    { value: "29", text: "Bouvet Island" },
    { value: "30", text: "Brazil" },
    { value: "31", text: "British Indian Ocean Territory" },
    { value: "32", text: "Brunei Darussalam" },
    { value: "33", text: "Bulgaria" },
    { value: "34", text: "Burkina Faso" },
    { value: "35", text: "Burma" },
    { value: "36", text: "Burundi" },
    { value: "37", text: "Cambodia" },
    { value: "38", text: "Cameroon" },
    { value: "39", text: "Canada" },
    { value: "40", text: "Cape Verde" },
    { value: "41", text: "Cayman Islands" },
    { value: "42", text: "Central African Republic" },
    { value: "43", text: "Chad" },
    { value: "44", text: "Chile" },
    { value: "45", text: "China" },
    { value: "46", text: "Christmas Island" },
    { value: "47", text: "Cocos (Keeling) Islands" },
    { value: "48", text: "Colombia" },
    { value: "49", text: "Comoros" },
    { value: "50", text: "Congo" },
    { value: "51", text: "Congo, the Democratic Republic of the" },
    { value: "52", text: "Cook Islands" },
    { value: "53", text: "Costa Rica" },
    { value: "54", text: "Cote d'Ivoire" },
    { value: "55", text: "Croatia" },
    { value: "56", text: "Cuba" },
    { value: "57", text: "Cyprus" },
    { value: "58", text: "Czech Republic" },
    { value: "59", text: "Denmark" },
    { value: "60", text: "Djibouti" },
    { value: "61", text: "Dominica" },
    { value: "62", text: "Dominican Republic" },
    { value: "63", text: "East Timor" },
    { value: "64", text: "Ecuador" },
    { value: "65", text: "Egypt" },
    { value: "66", text: "El Salvador" },
    { value: "67", text: "England" },
    { value: "68", text: "Equatorial Guinea" },
    { value: "69", text: "Eritrea" },
    { value: "71", text: "Estonia" },
    { value: "72", text: "Ethiopia" },
    { value: "73", text: "Falkland Islands" },
    { value: "74", text: "Faroe Islands" },
    { value: "75", text: "Fiji" },
    { value: "76", text: "Finland" },
    { value: "77", text: "France" },
    { value: "78", text: "French Guiana" },
    { value: "79", text: "French Polynesia" },
    { value: "80", text: "French Southern Territories" },
    { value: "81", text: "Gabon" },
    { value: "82", text: "Gambia" },
    { value: "83", text: "Georgia" },
    { value: "84", text: "Germany" },
    { value: "85", text: "Ghana" },
    { value: "86", text: "Gibraltar" },
    { value: "88", text: "Greece" },
    { value: "89", text: "Greenland" },
    { value: "90", text: "Grenada" },
    { value: "91", text: "Guadeloupe" },
    { value: "92", text: "Guam" },
    { value: "93", text: "Guatemala" },
    { value: "245", text: "Guernsey" },
    { value: "94", text: "Guinea" },
    { value: "95", text: "Guinea-Bissau" },
    { value: "96", text: "Guyana" },
    { value: "97", text: "Haiti" },
    { value: "98", text: "Heard and Mc Donald Islands" },
    { value: "99", text: "Honduras" },
    { value: "100", text: "Hong Kong" },
    { value: "101", text: "Hungary" },
    { value: "102", text: "Iceland" },
    { value: "103", text: "India" },
    { value: "104", text: "Indonesia" },
    { value: "108", text: "Iran" },
    { value: "109", text: "Iraq" },
    { value: "105", text: "Ireland" },
    { value: "251", text: "Isle of Man" },
    { value: "106", text: "Israel" },
    { value: "107", text: "Italy" },
    { value: "110", text: "Jamaica" },
    { value: "111", text: "Japan" },
    { value: "250", text: "Jersey" },
    { value: "112", text: "Jordan" },
    { value: "113", text: "Kazakhstan" },
    { value: "114", text: "Kenya" },
    { value: "115", text: "Kiribati" },
    { value: "116", text: "Korea, Republic of" },
    { value: "249", text: "Kosovo" },
    { value: "118", text: "Kuwait" },
    { value: "119", text: "Kyrgyzstan" },
    { value: "120", text: "Lao People's Democratic Republic" },
    { value: "121", text: "Latvia" },
    { value: "122", text: "Lebanon" },
    { value: "123", text: "Lesotho" },
    { value: "124", text: "Liberia" },
    { value: "125", text: "Liechtenstein" },
    { value: "126", text: "Lithuania" },
    { value: "127", text: "Luxembourg" },
    { value: "128", text: "Macau" },
    { value: "129", text: "Macedonia" },
    { value: "130", text: "Madagascar" },
    { value: "131", text: "Malawi" },
    { value: "132", text: "Malaysia" },
    { value: "133", text: "Maldives" },
    { value: "134", text: "Mali" },
    { value: "135", text: "Malta" },
    { value: "136", text: "Marshall Islands" },
    { value: "137", text: "Martinique" },
    { value: "138", text: "Mauritania" },
    { value: "139", text: "Mauritius" },
    { value: "140", text: "Mayotte" },
    { value: "141", text: "Mexico" },
    { value: "142", text: "Micronesia, Federated States of" },
    { value: "143", text: "Moldova, Republic of" },
    { value: "144", text: "Monaco" },
    { value: "145", text: "Mongolia" },
    { value: "248", text: "Montenegro" },
    { value: "146", text: "Montserrat" },
    { value: "147", text: "Morocco" },
    { value: "148", text: "Mozambique" },
    { value: "149", text: "Myanmar" },
    { value: "150", text: "Namibia" },
    { value: "151", text: "Nauru" },
    { value: "152", text: "Nepal" },
    { value: "153", text: "Netherlands" },
    { value: "154", text: "Netherlands Antilles" },
    { value: "155", text: "New Caledonia" },
    { value: "156", text: "New Zealand" },
    { value: "157", text: "Nicaragua" },
    { value: "158", text: "Niger" },
    { value: "159", text: "Nigeria" },
    { value: "160", text: "Niue" },
    { value: "161", text: "Norfolk Island" },
    { value: "162", text: "Northern Ireland" },
    { value: "163", text: "Northern Mariana Islands" },
    { value: "164", text: "Norway" },
    { value: "165", text: "Oman" },
    { value: "166", text: "Pakistan" },
    { value: "167", text: "Palau" },
    { value: "168", text: "Panama" },
    { value: "169", text: "Papua New Guinea" },
    { value: "170", text: "Paraguay" },
    { value: "171", text: "Peru" },
    { value: "172", text: "Philippines" },
    { value: "173", text: "Pitcairn" },
    { value: "174", text: "Poland" },
    { value: "175", text: "Portugal" },
    { value: "176", text: "Puerto Rico" },
    { value: "177", text: "Qatar" },
    { value: "178", text: "Reunion" },
    { value: "179", text: "Romania" },
    { value: "180", text: "Russia" },
    { value: "181", text: "Rwanda" },
    { value: "182", text: "Saint Kitts and Nevis" },
    { value: "183", text: "Saint Lucia" },
    { value: "184", text: "Saint Vincent and the Grenadines" },
    { value: "185", text: "Samoa (Independent)" },
    { value: "186", text: "San Marino" },
    { value: "187", text: "Sao Tome and Principe" },
    { value: "188", text: "Saudi Arabia" },
    { value: "189", text: "Scotland" },
    { value: "190", text: "Senegal" },
    { value: "247", text: "Serbia" },
    { value: "191", text: "Serbia and Montenegro" },
    { value: "192", text: "Seychelles" },
    { value: "193", text: "Sierra Leone" },
    { value: "194", text: "Singapore" },
    { value: "195", text: "Slovakia" },
    { value: "196", text: "Slovenia" },
    { value: "197", text: "Solomon Islands" },
    { value: "198", text: "Somalia" },
    { value: "199", text: "South Africa" },
    { value: "200", text: "South Georgia and the South Sandwich Islands" },
    { value: "201", text: "South Korea" },
    { value: "202", text: "Spain" },
    { value: "203", text: "Sri Lanka" },
    { value: "204", text: "St. Helena" },
    { value: "205", text: "St. Pierre and Miquelon" },
    { value: "246", text: "Sudan, Republic of" },
    { value: "206", text: "Suriname" },
    { value: "207", text: "Svalbard and Jan Mayen Islands" },
    { value: "208", text: "Swaziland" },
    { value: "209", text: "Sweden" },
    { value: "210", text: "Switzerland" },
    { value: "211", text: "Taiwan" },
    { value: "212", text: "Tajikistan" },
    { value: "213", text: "Tanzania" },
    { value: "214", text: "Thailand" },
    { value: "215", text: "Togo" },
    { value: "216", text: "Tokelau" },
    { value: "217", text: "Tonga" },
    { value: "218", text: "Trinidad" },
    { value: "219", text: "Trinidad and Tobago" },
    { value: "220", text: "Tunisia" },
    { value: "221", text: "Turkey" },
    { value: "222", text: "Turkmenistan" },
    { value: "223", text: "Turks and Caicos Islands" },
    { value: "224", text: "Tuvalu" },
    { value: "225", text: "Uganda" },
    { value: "226", text: "Ukraine" },
    { value: "227", text: "United Arab Emirates" },
    { value: "228", text: "United Kingdom" },
    { value: "229", text: "United States" },
    { value: "230", text: "United States Minor Outlying Islands" },
    { value: "231", text: "Uruguay" },
    { value: "232", text: "Uzbekistan" },
    { value: "233", text: "Vanuatu" },
    { value: "234", text: "Vatican City State (Holy See)" },
    { value: "235", text: "Venezuela" },
    { value: "236", text: "Viet Nam" },
    { value: "237", text: "Virgin Islands (British)" },
    { value: "238", text: "Virgin Islands (U.S.)" },
    { value: "239", text: "Wales" },
    { value: "240", text: "Wallis and Futuna Islands" },
    { value: "241", text: "Western Sahara" },
    { value: "242", text: "Yemen" },
    { value: "243", text: "Zambia" },
    { value: "244", text: "Zimbabwe" },
];
